/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Arrays;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    private Solution solution;
    private Result result;

    @BeforeEach
    void setUp() {
        solution = new Solution();
        result = new Result();
    }

    @Test
    void sample() {
        assertEquals(19, result.hourglassSum();
    }
}
